/proc/pencode2html(t)
	t = pencode_acs2html(t)
	t = replacetext(t, "\n", "<BR>")
	t = replacetext(t, "\[center\]", "<center>")
	t = replacetext(t, "\[/center\]", "</center>")
	t = replacetext(t, "\[br\]", "<BR>")
	t = replacetext(t, "\[b\]", "<B>")
	t = replacetext(t, "\[/b\]", "</B>")
	t = replacetext(t, "\[i\]", "<I>")
	t = replacetext(t, "\[/i\]", "</I>")
	t = replacetext(t, "\[u\]", "<U>")
	t = replacetext(t, "\[/u\]", "</U>")
	t = replacetext(t, "\[time\]", "[gameTimestamp("hh:mm")]")
	t = replacetext(t, "\[date\]", "[time2text(world.timeofday, "YYYY-MM-DD")]")
	t = replacetext(t, "\[large\]", "<font size=\"4\">")
	t = replacetext(t, "\[/large\]", "</font>")
	t = replacetext(t, "\[field\]", "<span class=\"paper_field\"></span>")
	t = replacetext(t, "\[h1\]", "<H1>")
	t = replacetext(t, "\[/h1\]", "</H1>")
	t = replacetext(t, "\[h2\]", "<H2>")
	t = replacetext(t, "\[/h2\]", "</H2>")
	t = replacetext(t, "\[h3\]", "<H3>")
	t = replacetext(t, "\[/h3\]", "</H3>")
	t = replacetext(t, "\[*\]", "<li>")
	t = replacetext(t, "\[hr\]", "<HR>")
	t = replacetext(t, "\[small\]", "<font size = \"1\">")
	t = replacetext(t, "\[/small\]", "</font>")
	t = replacetext(t, "\[ulist\]", "<ul>")
	t = replacetext(t, "\[/ulist\]", "</ul>")
	t = replacetext(t, "\[list\]", "<ul>")
	t = replacetext(t, "\[/list\]", "</ul>")
	t = replacetext(t, "\[olist\]", "<ol>")
	t = replacetext(t, "\[/olist\]", "</ol>")
	t = replacetext(t, "\[table\]", "<table border=1 cellspacing=0 cellpadding=3 style='border: 1px solid black;'>")
	t = replacetext(t, "\[/table\]", "</td></tr></table>")
	t = replacetext(t, "\[grid\]", "<table>")
	t = replacetext(t, "\[/grid\]", "</td></tr></table>")
	t = replacetext(t, "\[row\]", "</td><tr>")
	t = replacetext(t, "\[cell\]", "<td>")
	t = replacetext(t, "\[editorbr\]", "")
	t = replacetext(t, "\[scplogo\]", "<img src = scplogo.png>")
	t = replacetext(t, "\[ethicslogo\]", "<img src = ethics.png>")
	t = replacetext(t, "\[o5logo\]", "<img src = o5.png>")
	t = replacetext(t, "\[adminlogo\]", "<img src = admin.png>")
	t = replacetext(t, "\[englogo\]", "<img src = eng.png>")
	t = replacetext(t, "\[mtflogo\]", "<img src = mtf.png>")
	t = replacetext(t, "\[loglogo\]", "<img src = log.png>")
	t = replacetext(t, "\[manlogo\]", "<img src = man.png>")
	t = replacetext(t, "\[medlogo\]", "<img src = med.png>")
	t = replacetext(t, "\[scilogo\]", "<img src = sci.png>")
	t = replacetext(t, "\[seclogo\]", "<img src = sec.png>")
	t = replacetext(t, "\[isdlogo\]", "<img src = isd.png>")
	t = replacetext(t, "\[dealogo\]", "<img src = dea.png>")
	t = replacetext(t, "\[intlogo\]", "<img src = int.png>")
	t = replacetext(t, "\[triblogo\]", "<img src = trib.png>")
	t = replacetext(t, "\[aiadlogo\]", "<img src = aiad.png>")
	t = replacetext(t, "\[amdlogo\]", "<img src = amd.png>")
	t = replacetext(t, "\[dcdlogo\]", "<img src = dcd.png>")
	t = replacetext(t, "\[fsdlogo\]", "<img src = fsd.png>")
	t = replacetext(t, "\[misilogo\]", "<img src = misi.png>")
	t = replacetext(t, "\[patalogo\]", "<img src = pata.png>")
	t = replacetext(t, "\[raisalogo\]", "<img src = raisa.png>")
	t = replacetext(t, "\[goclogo\]", "<img src = ungoc.png>")
	t = replacetext(t, "\[uiulogo\]", "<img src = uiu.png>")
	t = replacetext(t, "\[mcdlogo\]", "<img src = mcd.png>")
	t = replacetext(t, "\[grlogo\]", "<img src = gr.png>")
	t = replacetext(t, "\[arlogo\]", "<img src = ar.png>")
	t = replacetext(t, "\[cilogo\]", "<img src = ci.png>")
	t = replacetext(t, "\[shlogo\]", "<img src = sh.png>")
	t = replacetext(t, "\[cotbglogo\]", "<img src = cotbg.png>")
	t = replacetext(t, "\[coclogo\]", "<img src = coc.png>")
	t = replacetext(t, "\[cmaxlogo\]", "<img src = cmax.png>")
	t = replacetext(t, "\[mcflogo\]", "<img src = mcf.png>")
	t = replacetext(t, "\[wwslogo\]", "<img src = wws.png>")
	t = replacetext(t, "\[spclogo\]", "<img src = spc.png>")
	t = replacetext(t, "\[redacted\]", "<span class=\"redacted\">R E D A C T E D</span>")
	return t

/proc/digitalPencode2html(text)
	text = replacetext(text, "\[pre\]", "<pre>")
	text = replacetext(text, "\[/pre\]", "</pre>")
	text = replacetext(text, "\[fontred\]", "<font color=\"red\">")
	text = replacetext(text, "\[fontblue\]", "<font color=\"blue\">")
	text = replacetext(text, "\[fontgreen\]", "<font color=\"green\">")
	text = replacetext(text, "\[/font\]", "</font>")
	return pencode2html(text)

/proc/pencode_acs2html(text)
	var/regex/scanner_nosecondary = new(@"\[acs item_number=(\w+) clearance_level=(\w+) containment_class=(\w+) disruption_class=(\w+) risk_class=(\w+)\]", "g")
	var/regex/scanner_secondary = new(@"\[acs item_number=(\w+) clearance_level=(\w+) containment_class=(\w+) secondary_class=(\w+) disruption_class=(\w+) risk_class=(\w+)\]", "g")
	var/newtext = text
	newtext = scanner_nosecondary.Replace(newtext, @{"<div class="acs-hybrid-text-bar acs-hybrid-version acs-clear-$2 acs-$3 acs-$4 acs-$5"><div class="acs-item"><span><strong>Item#:</strong>$1</span></div><div class="acs-clear"><strong>Clearance Level $2:</strong> <span class="clearance-level-text">Clearance</span></div><div class="acs-contain-container"><div class="acs-contain"><div class="acs-text"><span><strong>Containment Class:</strong></span> <span>$3</span></div><div class="acs-icon"><img src="http://scp-wiki.wdfiles.com/local--files/component%3Aanomaly-class-bar/$3-icon.svg" alt=""></div></div><div class="acs-secondary"><div class="acs-text"><span><strong>Secondary Class:</strong></span> <span></span></div><div class="acs-icon"><img></div></div></div><div class="acs-disrupt"><div class="acs-text"><strong>Disruption Class:</strong> <span class="disruption-class-number">#</span>/$4</div><div class="acs-icon"><img src="http://scp-wiki.wdfiles.com/local--files/component%3Aanomaly-class-bar/$4-icon.svg" alt=""></div></div><div class="acs-risk"><div class="acs-text"><strong>Risk Class:</strong> <span class="risk-class-number">#</span>/$5</div><div class="acs-icon"><img src="http://scp-wiki.wdfiles.com/local--files/component%3Aanomaly-class-bar/$5-icon.svg" alt=""></div></div></div>"})
	newtext = scanner_secondary.Replace(newtext, @{"<div class="acs-hybrid-text-bar acs-yes acs-hybrid-version acs-clear-$2 acs-$3 acs-$4 acs-$5 acs-$6"><div class="acs-item"><span><strong>Item#:</strong>$1</span></div><div class="acs-clear"><strong>Clearance Level $2:</strong> <span class="clearance-level-text">Clearance</span></div><div class="acs-contain-container"><div class="acs-contain"><div class="acs-text"><span><strong>Containment Class:</strong></span> <span>$3</span></div><div class="acs-icon"><img src="http://scp-wiki.wdfiles.com/local--files/component%3Aanomaly-class-bar/$3-icon.svg" alt=""></div></div><div class="acs-secondary"><div class="acs-text"><span><strong>Secondary Class:</strong></span> <span>$4</span></div><div class="acs-icon"><img src="http://scp-wiki.wdfiles.com/local--files/component%3Aanomaly-class-bar/$4-icon.svg" alt=""></div></div></div><div class="acs-disrupt"><div class="acs-text"><strong>Disruption Class:</strong> <span class="disruption-class-number">#</span>/$5</div><div class="acs-icon"><img src="http://scp-wiki.wdfiles.com/local--files/component%3Aanomaly-class-bar/$5-icon.svg" alt=""></div></div><div class="acs-risk"><div class="acs-text"><strong>Risk Class:</strong> <span class="risk-class-number">#</span>/$6</div><div class="acs-icon"><img src="http://scp-wiki.wdfiles.com/local--files/component%3Aanomaly-class-bar/$6-icon.svg" alt=""></div></div></div>"})
	return newtext
