// Foundation-19 Access Defines
// These are the access levels and defines needed for Foundation-19 jobs

// Region defines
#define ACCESS_REGION_NONE          -1
#define ACCESS_REGION_ALL           0
#define ACCESS_REGION_SECURITY      1
#define ACCESS_REGION_MEDBAY        2
#define ACCESS_REGION_RESEARCH      3
#define ACCESS_REGION_ENGINEERING   4
#define ACCESS_REGION_COMMAND       5
#define ACCESS_REGION_GENERAL       6
#define ACCESS_REGION_SUPPLY        7
#define ACCESS_REGION_SERVICE       8
#define ACCESS_REGION_CONTAINMENT   9
#define ACCESS_REGION_OFFSITE       10

// Access type defines
#define ACCESS_TYPE_NONE        (1<<0)
#define ACCESS_TYPE_CENTCOM     (1<<1)
#define ACCESS_TYPE_STATION     (1<<2)
#define ACCESS_TYPE_SYNDICATE   (1<<3)
#define ACCESS_TYPE_INNATE      (1<<4) // Department levels
#define ACCESS_TYPE_CONTAINMENT (1<<5)
#define ACCESS_TYPE_UNGOC       (1<<6)
#define ACCESS_TYPE_ALL         (~ACCESS_TYPE_NONE)

// Level access defines
#define ACCESS_SECURITY_LVL1 "ACCESS_SECURITY_LEVEL1" // Security Lobby
#define ACCESS_SECURITY_LVL2 "ACCESS_SECURITY_LEVEL2" // LCZ
#define ACCESS_SECURITY_LVL3 "ACCESS_SECURITY_LEVEL3" // HCZ
#define ACCESS_SECURITY_LVL4 "ACCESS_SECURITY_LEVEL4" // Zone Commander
#define ACCESS_SECURITY_LVL5 "ACCESS_SECURITY_LEVEL5" // Guard Commander

#define ACCESS_SCIENCE_LVL1 "ACCESS_SCIENCE_LEVEL1" // Lobby
#define ACCESS_SCIENCE_LVL2 "ACCESS_SCIENCE_LEVEL2" // Research Associate
#define ACCESS_SCIENCE_LVL3 "ACCESS_SCIENCE_LEVEL3" // Researcher
#define ACCESS_SCIENCE_LVL4 "ACCESS_SCIENCE_LEVEL4" // Senior Researcher
#define ACCESS_SCIENCE_LVL5 "ACCESS_SCIENCE_LEVEL5" // Research Director

#define ACCESS_MEDICAL_LVL1 "ACCESS_MEDICAL_LEVEL1" // Psych
#define ACCESS_MEDICAL_LVL2 "ACCESS_MEDICAL_LEVEL2" // Paramedic, Chemist
#define ACCESS_MEDICAL_LVL3 "ACCESS_MEDICAL_LEVEL3" // Doctor, Surgeon
#define ACCESS_MEDICAL_LVL4 "ACCESS_MEDICAL_LEVEL4" // Virologist
#define ACCESS_MEDICAL_LVL5 "ACCESS_MEDICAL_LEVEL5" // Chief Medical Officer

#define ACCESS_ENGINEERING_LVL1 "ACCESS_ENGINEERING_LEVEL1" // Junior Engineer
#define ACCESS_ENGINEERING_LVL2 "ACCESS_ENGINEERING_LEVEL2" // Engineer
#define ACCESS_ENGINEERING_LVL3 "ACCESS_ENGINEERING_LEVEL3" // Senior Engineer, Comms Programmer
#define ACCESS_ENGINEERING_LVL4 "ACCESS_ENGINEERING_LEVEL4" // Containment Engineer
#define ACCESS_ENGINEERING_LVL5 "ACCESS_ENGINEERING_LEVEL5" // Chief Engineer

#define ACCESS_ADMIN_LVL1 "ACCESS_ADMIN_LEVEL1" // Command Lobby, Logistics, Comms
#define ACCESS_ADMIN_LVL2 "ACCESS_ADMIN_LEVEL2" // 05 Rep, Logistics Officer, Comms Tech
#define ACCESS_ADMIN_LVL3 "ACCESS_ADMIN_LEVEL3" // AIC Observation
#define ACCESS_ADMIN_LVL4 "ACCESS_ADMIN_LEVEL4" // AIC Upload/Core
#define ACCESS_ADMIN_LVL5 "ACCESS_ADMIN_LEVEL5" // Site Director

// Special access defines
#define ACCESS_MTF "ACCESS_MTF"
#define ACCESS_TORCH_FAX "ACCESS_TORCH_FAX"
#define ACCESS_KEYAUTH "ACCESS_KEYCARD_AUTH"

// Communication access
#define ACCESS_ENG_COMMS "ACCESS_COMMS_ENGINEERING"
#define ACCESS_SCI_COMMS "ACCESS_COMMS_SCIENCE"
#define ACCESS_SEC_COMMS "ACCESS_COMMS_SECURITY"
#define ACCESS_LOG_COMMS "ACCESS_COMMS_LOGISTICS"
#define ACCESS_CIV_COMMS "ACCESS_COMMS_CIVILIAN"
#define ACCESS_MED_COMMS "ACCESS_COMMS_MEDICAL"
#define ACCESS_COM_COMMS "ACCESS_COMMS_COMMAND"

// D-Class access
#define ACCESS_DCLASS_KITCHEN "ACCESS_DCLASS_KITCHEN"
#define ACCESS_DCLASS_BOTANY "ACCESS_DCLASS_BOTANY"
#define ACCESS_DCLASS_MINING "ACCESS_DCLASS_MINING"
#define ACCESS_DCLASS_JANITORIAL "ACCESS_DCLASS_JANITORIAL"
#define ACCESS_DCLASS_MEDICAL "ACCESS_DCLASS_MEDICAL"
#define ACCESS_DCLASS_LUXURY "ACCESS_DCLASS_LUXURY"

// SCP containment access (basic set)
#define ACCESS_CONTAINMENT_SCP_173 "ACCESS_CONTAINMENT_SCP_173"
#define ACCESS_CONTAINMENT_SCP_096 "ACCESS_CONTAINMENT_SCP_096"
#define ACCESS_CONTAINMENT_SCP_049 "ACCESS_CONTAINMENT_SCP_049"
#define ACCESS_CONTAINMENT_SCP_106 "ACCESS_CONTAINMENT_SCP_106"
#define ACCESS_CONTAINMENT_SCP_079 "ACCESS_CONTAINMENT_SCP_079"
#define ACCESS_CONTAINMENT_SCP_087 "ACCESS_CONTAINMENT_SCP_087"
#define ACCESS_CONTAINMENT_SCP_113 "ACCESS_CONTAINMENT_SCP_113"
#define ACCESS_CONTAINMENT_SCP_131 "ACCESS_CONTAINMENT_SCP_131"
#define ACCESS_CONTAINMENT_SCP_343 "ACCESS_CONTAINMENT_SCP_343"
#define ACCESS_CONTAINMENT_SCP_513 "ACCESS_CONTAINMENT_SCP_513"
#define ACCESS_CONTAINMENT_SCP_895 "ACCESS_CONTAINMENT_SCP_895"
#define ACCESS_CONTAINMENT_SCP_914 "ACCESS_CONTAINMENT_SCP_914"
#define ACCESS_CONTAINMENT_SCP_999 "ACCESS_CONTAINMENT_SCP_999"

// Additional Foundation-19 specific access
#define ACCESS_FORENSICS_LOCKERS "ACCESS_FORENSICS"
#define ACCESS_TOX "ACCESS_TOXINS"
#define ACCESS_TOX_STORAGE "ACCESS_TOX_STORAGE"
#define ACCESS_EMERGENCY_STORAGE "ACCESS_EMERGENCY_STORAGE"
#define ACCESS_BRIDGE "ACCESS_BRIDGE"
#define ACCESS_CARGO_BOT "ACCESS_CARGO_BOT"
#define ACCESS_MANUFACTURING "ACCESS_MANUFACTURING"
#define ACCESS_VIROLOGY "ACCESS_VIRO"
#define ACCESS_NETWORK "ACCESS_NETWORK"
#define ACCESS_MINING_OFFICE "ACCESS_MINING_OFFICE"
#define ACCESS_HEADS_VAULT "ACCESS_VAULT"
#define ACCESS_SEC_DOORS "ACCESS_SEC_DOORS"
#define ACCESS_PSYCHIATRIST "ACCESS_PSYCHIATRIST"
#define ACCESS_XENOARCH "ACCESS_XENOARCH"
#define ACCESS_MEDICAL_EQUIP "ACCESS_MEDICAL_EQUIP"
#define ACCESS_HEADS "ACCESS_HEADS"
#define ACCESS_PSIADVISOR "ACCESS_PSIADVISOR"
#define ACCESS_ASCENT "ACCESS_ASCENT"

// Department flags
#define SEC 1
#define COM 2
#define LCZ 4
#define HCZ 8
#define EZ 16
