// Foundation-19 Access Defines
// SCP-specific additions that don't conflict with the numeric access system in code/__DEFINES/access.dm
// All duplicate defines are guarded with #ifndef to prevent override of the numeric system

// Region defines
#define ACCESS_REGION_NONE          -1
#define ACCESS_REGION_ALL           0
#define ACCESS_REGION_SECURITY      1
#define ACCESS_REGION_MEDBAY        2
#define ACCESS_REGION_RESEARCH      3
#define ACCESS_REGION_ENGINEERING   4
#define ACCESS_REGION_COMMAND       5
#define ACCESS_REGION_GENERAL       6
#define ACCESS_REGION_SUPPLY        7
#define ACCESS_REGION_SERVICE       8
#define ACCESS_REGION_CONTAINMENT   9
#define ACCESS_REGION_OFFSITE       10

// Access type defines
#define ACCESS_TYPE_NONE        (1<<0)
#define ACCESS_TYPE_CENTCOM     (1<<1)
#define ACCESS_TYPE_STATION     (1<<2)
#define ACCESS_TYPE_SYNDICATE   (1<<3)
#define ACCESS_TYPE_INNATE      (1<<4)
#define ACCESS_TYPE_CONTAINMENT (1<<5)
#define ACCESS_TYPE_UNGOC       (1<<6)
#define ACCESS_TYPE_ALL         (~ACCESS_TYPE_NONE)

// SCP Containment Access — Numeric range 50-99 (reserved, does not conflict with base 1-49)
#define ACCESS_CONTAINMENT_SCP_173 50
#define ACCESS_CONTAINMENT_SCP_096 51
#define ACCESS_CONTAINMENT_SCP_049 52
#define ACCESS_CONTAINMENT_SCP_106 53
#define ACCESS_CONTAINMENT_SCP_079 54
#define ACCESS_CONTAINMENT_SCP_087 55
#define ACCESS_CONTAINMENT_SCP_113 56
#define ACCESS_CONTAINMENT_SCP_131 57
#define ACCESS_CONTAINMENT_SCP_343 58
#define ACCESS_CONTAINMENT_SCP_513 59
#define ACCESS_CONTAINMENT_SCP_895 60
#define ACCESS_CONTAINMENT_SCP_914 61
#define ACCESS_CONTAINMENT_SCP_999 62
#define ACCESS_CONTAINMENT_SCP_012 63
#define ACCESS_CONTAINMENT_SCP_013 64
#define ACCESS_CONTAINMENT_SCP_017 65
#define ACCESS_CONTAINMENT_SCP_066 66
#define ACCESS_CONTAINMENT_SCP_078 67
#define ACCESS_CONTAINMENT_SCP_080 68
#define ACCESS_CONTAINMENT_SCP_082 69
#define ACCESS_CONTAINMENT_SCP_1102 70
#define ACCESS_CONTAINMENT_SCP_1471 71
#define ACCESS_CONTAINMENT_SCP_1499 72
#define ACCESS_CONTAINMENT_SCP_1507 73
#define ACCESS_CONTAINMENT_SCP_151 74
#define ACCESS_CONTAINMENT_SCP_178 75
#define ACCESS_CONTAINMENT_SCP_216 76
#define ACCESS_CONTAINMENT_SCP_247 77
#define ACCESS_CONTAINMENT_SCP_263 78
#define ACCESS_CONTAINMENT_SCP_280 79
#define ACCESS_CONTAINMENT_SCP_294 80
#define ACCESS_CONTAINMENT_SCP_3199 81
#define ACCESS_CONTAINMENT_SCP_3349 82
#define ACCESS_CONTAINMENT_SCP_347 83
#define ACCESS_CONTAINMENT_SCP_399 84
#define ACCESS_CONTAINMENT_SCP_409 85
#define ACCESS_CONTAINMENT_SCP_427 86
#define ACCESS_CONTAINMENT_SCP_500 87
#define ACCESS_CONTAINMENT_SCP_5000 88
#define ACCESS_CONTAINMENT_SCP_527 89
#define ACCESS_CONTAINMENT_SCP_714 90
#define ACCESS_CONTAINMENT_SCP_896 91
#define ACCESS_CONTAINMENT_SCP_966 92
#define ACCESS_CONTAINMENT_SCP_953 93
#define ACCESS_CONTAINMENT_SCP_1025 94
#define ACCESS_CONTAINMENT_SCP_1366 95

// MTF Access
#define ACCESS_MTF 96

// Foundation-specific functional access (numeric, 97-99)
#define ACCESS_TORCH_FAX 97
#define ACCESS_KEYAUTH 98
#define ACCESS_NETWORK 99

// SCP Zone Access
#define ACCESS_LCZ 100
#define ACCESS_HCZ 101
#define ACCESS_EZ 102
#define ACCESS_SURFACE 103

// Foundation Communication Channels (numeric)
#define ACCESS_ENG_COMMS 104
#define ACCESS_SCI_COMMS 105
#define ACCESS_SEC_COMMS 106
#define ACCESS_LOG_COMMS 107
#define ACCESS_CIV_COMMS 108
#define ACCESS_MED_COMMS 109
#define ACCESS_COM_COMMS 110

// Additional Foundation-19 functional access (numeric)
#define ACCESS_FORENSICS_LOCKERS 111
#define ACCESS_TOX 112
#define ACCESS_TOX_STORAGE 113
#define ACCESS_EMERGENCY_STORAGE 114
#define ACCESS_BRIDGE 115
#define ACCESS_CARGO_BOT 116
#define ACCESS_MANUFACTURING 117
#define ACCESS_VIROLOGY 118
#define ACCESS_MINING_OFFICE 119
#define ACCESS_HEADS_VAULT 120
#define ACCESS_SEC_DOORS 121
#define ACCESS_PSYCHIATRIST 122
#define ACCESS_XENOARCH 123
#define ACCESS_MEDICAL_EQUIP 124
#define ACCESS_HEADS 125
#define ACCESS_PSIADVISOR 126
#define ACCESS_ASCENT 127

// D-Class Kitchen Access (unique, not in base system)
#define ACCESS_DCLASS_KITCHEN 128

// Department flags
#define DEPT_SEC 1
#define DEPT_COM 2
#define DEPT_LCZ 4
#define DEPT_HCZ 8
#define DEPT_EZ 16
