#define SCANNER_TIER_BASIC 1
#define SCANNER_TIER_ADVANCED 2
#define SCANNER_TIER_EXPERIMENTAL 3

#define FORENSIC_SCAN_TIER_BASIC 1
#define FORENSIC_SCAN_TIER_ADVANCED 2
#define FORENSIC_SCAN_TIER_EXPERIMENTAL 3
