/obj/item/scp_scanner/proc/scan_anomaly(atom/target, mob/living/user)
	if(!target.SCP)
		return
	var/list/output = list()
	switch(scanner_tier)
		if(SCANNER_TIER_BASIC)
			output += span_warning("Anomalous readings detected on [target]. Recommend further analysis.")
		if(SCANNER_TIER_ADVANCED)
			output += span_warning("Anomalous readings detected on [target].")
			output += span_notice("Designation: SCP-[target.SCP.designation]")
			output += span_notice("Classification: [target.SCP.classification]")
		if(SCANNER_TIER_EXPERIMENTAL)
			output += span_warning("Anomalous readings detected on [target].")
			output += span_notice("Designation: SCP-[target.SCP.designation]")
			output += span_notice("Classification: [target.SCP.classification]")
			output += span_notice("Name: [target.SCP.name]")
			output += span_userdanger("WARNING: Cognitohazard risk detected. Maintain safe distance.")
			if(target.forensic_holder)
				var/datum/forensic_holder/fh = target.forensic_holder
				if(LAZYLEN(fh.anomaly_evidence))
					output += span_notice("Anomalous forensic signatures present. Full forensic analysis recommended.")
	last_scan_result = jointext(output, "\n")
	to_chat(user, last_scan_result)
