#define COGNITOHAZARD_PROTECTION_NONE 0
#define COGNITOHAZARD_PROTECTION_PARTIAL 0.5
#define COGNITOHAZARD_PROTECTION_FULL 1

#define COGNITOHAZARD_TIER_UNEASE 1
#define COGNITOHAZARD_TIER_PARANOIA 2
#define COGNITOHAZARD_TIER_HALLUCINATION 3
#define COGNITOHAZARD_TIER_COMPULSION 4
#define COGNITOHAZARD_TIER_BREAKDOWN 5

#define COGNITOHAZARD_DISTANCE_CLOSE 1
#define COGNITOHAZARD_DISTANCE_MEDIUM 2
#define COGNITOHAZARD_DISTANCE_FAR 3

#define COGNITOHAZARD_TIER_1_THRESHOLD 10
#define COGNITOHAZARD_TIER_2_THRESHOLD 25
#define COGNITOHAZARD_TIER_3_THRESHOLD 50
#define COGNITOHAZARD_TIER_4_THRESHOLD 75
#define COGNITOHAZARD_TIER_5_THRESHOLD 95

#define COGNITOHAZARD_DECAY_RATE 0.5
#define COGNITOHAZARD_ACCUMULATION_RATE 0.3
#define COGNITOHAZARD_DARKNESS_MULTIPLIER 1.5

#define TRAIT_SCP610_IMMUNE "scp610_immune"
