#ifndef COOKING_DEFINES
#define COOKING_DEFINES
#define APPLIANCE_MIX		(1<<0)
#define APPLIANCE_FRYER		(1<<1)
#define APPLIANCE_OVEN		(1<<2)
#define APPLIANCE_SKILLET	(1<<3)
#define APPLIANCE_SAUCEPAN	(1<<4)
#define APPLIANCE_POT		(1<<5)
#define APPLIANCE_GRILL		(1<<6)
#define APPLIANCE_MICROWAVE	(1<<7)
#define APPLIANCE_CANDY		(1<<8)
#define APPLIANCE_CEREAL	(1<<9)

#define RECIPE_REAGENT_REPLACE	0
#define RECIPE_REAGENT_MAX		1
#define RECIPE_REAGENT_MIN		2
#define RECIPE_REAGENT_SUM		3

#define COOK_CHECK_FAIL		0
#define COOK_CHECK_EXTRA	1
#define COOK_CHECK_EXACT	2

#define COOK_STAGE_RAW		0
#define COOK_STAGE_COOKED	1
#define COOK_STAGE_BURNT	2
#endif
