// SCP Interaction & Experiment Defines
// Single source of truth — do NOT duplicate in other files

// ===== INTERACTION TYPES =====
#define INTERACTION_TYPE_OBSERVATION 1
#define INTERACTION_TYPE_COMBAT 2
#define INTERACTION_TYPE_CONTAINMENT 3
#define INTERACTION_TYPE_RESEARCH 4
#define INTERACTION_TYPE_COMMUNICATION 5
#define INTERACTION_TYPE_EXPERIMENT 6
#define INTERACTION_TYPE_CARE 7
#define INTERACTION_TYPE_EXPLORATION 8
#define INTERACTION_TYPE_SURVIVAL 9
#define INTERACTION_TYPE_MEDICAL 10

// ===== INTERACTION RISK =====
#define INTERACTION_RISK_NONE 0
#define INTERACTION_RISK_LOW 1
#define INTERACTION_RISK_MEDIUM 2
#define INTERACTION_RISK_HIGH 3
#define INTERACTION_RISK_CRITICAL 4

// ===== EXPERIMENT TYPES =====
#define EXPERIMENT_TYPE_BEHAVIORAL 1
#define EXPERIMENT_TYPE_CONTAINMENT 2
#define EXPERIMENT_TYPE_INTERACTION 3
#define EXPERIMENT_TYPE_HAZARD 4
#define EXPERIMENT_TYPE_MEDICAL 5
#define EXPERIMENT_TYPE_TECHNICAL 6
#define EXPERIMENT_TYPE_COGNITIVE 7
#define EXPERIMENT_TYPE_EXPLORATION 8
#define EXPERIMENT_TYPE_CARE 9
#define EXPERIMENT_TYPE_OBSERVATION 10

// ===== EXPERIMENT RISK =====
#define EXPERIMENT_RISK_MINIMAL 1
#define EXPERIMENT_RISK_LOW 2
#define EXPERIMENT_RISK_MEDIUM 3
#define EXPERIMENT_RISK_HIGH 4
#define EXPERIMENT_RISK_CRITICAL 5

// ===== EXPERIMENT ACCESS =====
#define EXPERIMENT_ACCESS_NONE 0
#define EXPERIMENT_ACCESS_OBSERVE 1
#define EXPERIMENT_ACCESS_ASSIST 2
#define EXPERIMENT_ACCESS_STANDARD 3
#define EXPERIMENT_ACCESS_ADVANCED 4
#define EXPERIMENT_ACCESS_FULL 5

// ===== EXPERIMENT PHASES =====
#define EXPERIMENT_PHASE_PREPARATION 1
#define EXPERIMENT_PHASE_EXECUTION 2
#define EXPERIMENT_PHASE_OBSERVATION 3
#define EXPERIMENT_PHASE_CONCLUSION 4

// ===== EXPERIMENT OUTCOMES =====
#define EXPERIMENT_OUTCOME_SUCCESS_MAJOR 1
#define EXPERIMENT_OUTCOME_SUCCESS 2
#define EXPERIMENT_OUTCOME_SUCCESS_MINOR 3
#define EXPERIMENT_OUTCOME_NEUTRAL 4
#define EXPERIMENT_OUTCOME_FAILURE_MINOR 5
#define EXPERIMENT_OUTCOME_FAILURE 6
#define EXPERIMENT_OUTCOME_FAILURE_MAJOR 7
#define EXPERIMENT_OUTCOME_CATASTROPHIC 8

// ===== D-CLASS TRUST LEVELS =====
#define DCLASS_TRUST_HOSTILE 0
#define DCLASS_TRUST_SUSPICIOUS 1
#define DCLASS_TRUST_NEUTRAL 2
#define DCLASS_TRUST_COOPERATIVE 3
#define DCLASS_TRUST_TRUSTED 4

// ===== D-CLASS STATUS =====
#define DCLASS_STATUS_GENERAL 0
#define DCLASS_STATUS_TEST_SUBJECT 1
#define DCLASS_STATUS_MEDICAL_SUBJECT 2
#define DCLASS_STATUS_CONTAINMENT_ASSIST 3

// ===== D-CLASS FACTIONS =====
#define DCLASS_FACTION_NONE 0
#define DCLASS_FACTION_REBELS 1
#define DCLASS_FACTION_COLLABORATORS 2
#define DCLASS_FACTION_SURVIVORS 3
