/datum/achievement_manager/proc/register_foundation_job_achievements()
	register_achievement(new /datum/achievement("job_site_director_veteran", "Site Director Veteran", "Gain 1000 experience as Site Director", "job", "silver"))
	register_achievement(new /datum/achievement("job_site_director_expert", "Site Director Expert", "Gain 5000 experience as Site Director", "job", "gold"))
	register_achievement(new /datum/achievement("job_site_director_master", "Site Director Master", "Gain 10000 experience as Site Director", "job", "platinum"))
	register_achievement(new /datum/achievement("job_lcz_guard_veteran", "LCZ Guard Veteran", "Gain 1000 experience as LCZ Guard", "job", "silver"))
	register_achievement(new /datum/achievement("job_mtf_operative_veteran", "MTF Operative Veteran", "Gain 1000 experience as MTF Operative", "job", "silver"))
	register_achievement(new /datum/achievement("job_mtf_commander_veteran", "MTF Commander Veteran", "Gain 1000 experience as MTF Commander", "job", "gold"))
	register_achievement(new /datum/achievement("job_medical_doctor_veteran", "Medical Doctor Veteran", "Gain 1000 experience as Medical Doctor", "job", "silver"))
	register_achievement(new /datum/achievement("job_surgeon_veteran", "Surgeon Veteran", "Gain 1000 experience as Surgeon", "job", "silver"))
	register_achievement(new /datum/achievement("job_virologist_veteran", "Virologist Veteran", "Gain 1000 experience as Virologist", "job", "silver"))
	register_achievement(new /datum/achievement("job_researcher_veteran", "Researcher Veteran", "Gain 1000 experience as Researcher", "job", "silver"))
	register_achievement(new /datum/achievement("job_senior_researcher_veteran", "Senior Researcher Veteran", "Gain 1000 experience as Senior Researcher", "job", "silver"))
	register_achievement(new /datum/achievement("job_field_agent_veteran", "Field Agent Veteran", "Gain 1000 experience as Field Agent", "job", "silver"))
	register_achievement(new /datum/achievement("job_engineer_veteran", "Engineer Veteran", "Gain 1000 experience as Engineer", "job", "silver"))
	register_achievement(new /datum/achievement("job_containment_engineer_veteran", "Containment Engineer Veteran", "Gain 1000 experience as Containment Engineer", "job", "silver"))
	register_achievement(new /datum/achievement("job_quartermaster_veteran", "Quartermaster Veteran", "Gain 1000 experience as Quartermaster", "job", "silver"))
	register_achievement(new /datum/achievement("job_shaft_miner_veteran", "Shaft Miner Veteran", "Gain 1000 experience as Shaft Miner", "job", "silver"))
	register_achievement(new /datum/achievement("job_cook_veteran", "Cook Veteran", "Gain 1000 experience as Cook", "job", "silver"))
	register_achievement(new /datum/achievement("job_chaplain_veteran", "Chaplain Veteran", "Gain 1000 experience as Chaplain", "job", "silver"))
	register_achievement(new /datum/achievement("job_dclass_general_veteran", "D-Class Personnel Veteran", "Gain 1000 experience as D-Class Personnel", "job", "bronze"))
	register_achievement(new /datum/achievement("job_dclass_research_veteran", "D-Class Research Veteran", "Gain 1000 experience as D-Class Research", "job", "silver"))
	register_achievement(new /datum/achievement("job_site_director_dedicated", "Dedicated Site Director", "Play 10 rounds as Site Director", "job", "bronze"))
	register_achievement(new /datum/achievement("job_mtf_operative_dedicated", "Dedicated MTF Operative", "Play 10 rounds as MTF Operative", "job", "silver"))
	register_achievement(new /datum/achievement("job_researcher_dedicated", "Dedicated Researcher", "Play 10 rounds as Researcher", "job", "bronze"))
	register_achievement(new /datum/achievement("job_containment_breach_responder", "Containment Breach Responder", "Successfully respond to 5 containment breaches", "job", "gold"))
	register_achievement(new /datum/achievement("job_scp_researcher", "SCP Researcher", "Conduct 20 SCP research interactions", "job", "silver"))
	register_achievement(new /datum/achievement("job_medical_specialist", "Medical Specialist", "Perform 50 medical procedures", "job", "silver"))
	register_achievement(new /datum/achievement("job_engineering_master", "Engineering Master", "Complete 25 engineering projects", "job", "silver"))
	register_achievement(new /datum/achievement("job_security_operator", "Security Operator", "Conduct 30 security operations", "job", "silver"))
	register_achievement(new /datum/achievement("job_dclass_tester", "D-Class Tester", "Participate in 40 D-Class tests", "job", "silver"))
